# Generated by Django 5.1.3 on 2024-11-18 01:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=100)),
                ('Apellido', models.CharField(max_length=100)),
                ('Fecha_Nacimiento', models.DateField()),
                ('Sexo', models.CharField(choices=[('male', 'Masculino'), ('female', 'Femenino'), ('other', 'Otro')], max_length=10)),
                ('Cedula', models.CharField(max_length=10, unique=True)),
                ('Contrasenia', models.CharField(max_length=128)),
                ('sector', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='signup.sector')),
            ],
        ),
    ]
